### ISSUE TITLE
Animation sprite position issues

### ISSUE THREAD

**Issue by bnovakovic** [wojtossfm/godot_scml_importer#32]
Continuing from Issue #31 . I had to make another issue because this one is a bit tricky. 

**Godot version**: 4.3
**Spriter version**: Release 11 - Pro version.

I have purchased [Explorer character](https://www.gamedeveloperstudio.com/graphics/viewgraphic.php?item=1r6w4q805l5b592i6s). And, when I import it, not all assets are positioned normally. I am unable to fix it by editing the SCML and resaving it. Here is the screenshot: 
There are two visible issues.
1. Hat is not positioned normally
2. Left hand animation is junky and not as same as on the Spriter. 

Logs show warning. Here is the info: https://pastebin.com/MVQGuvdK

![image](https://github.com/user-attachments/assets/fc763c3e-fe8b-4a61-b38f-2341a97c4898)

Same animation worked normally without any edits in MonoGame and using their official API.

Now for the tricky part. I have purchased this asset, but I have received permission to give it to you if you do not distribute it further. I do need some email, in order to be able to send this to you.

**Comment by bnovakovic** [comment]
@wojtossfm I have added you to my repository where you will have access to this asset. Read `readme.md` and let me know if you need any assistance.

**Comment by wojtossfm** [comment]
> Now for the tricky part. I have purchased this asset, but I have received permission to give it to you if you do not distribute it further. I do need some email, in order to be able to send this to you.

It is great that you received permission for this. Indeed I wouldn't use such an asset for myself even. I always treat such samples as "reproduction of issues" only. I already have a couple such cases stored locally that I try to verify continue to work as I make changes. I've never had time to add proper tests for these that would reduce the overhead around this unfortunately.

> I have added you to my repository where you will have access to this asset. Read readme.md and let me know if you need any assistance.

This repository seems to contain the GreyGuy and not the explorer. Was this intended or by accident? Asking just so I know whether you will make it available through that repo or if you still would prefer I give you an email.

**Comment by bnovakovic** [comment]
> This repository seems to contain the GreyGuy and not the explorer. Was this intended or by accident? Asking just so I know whether you will make it available through that repo or if you still would prefer I give you an email.

Ah, my bad, I apologize. I have pushed new character. Sorry about that :)

**Comment by wojtossfm** [comment]
I believe I've tracked down at least parts of the issue.
 * z-index wasn't animated which meant that it wasn't adjusting the sorting for the different animations
 * seems a negative y scale needed special handling - I'm expecting something similar will be needed for negative x scale but I don't have an example to check with.

I'll still need to look at the animation speed at some point but not sure when I'll have time. Will you manage to see if things are better with https://github.com/wojtossfm/godot_scml_importer/tree/issue-32?

**Comment by bnovakovic** [comment]
Hey, I did check it out and issue with hat position is indeed fixed. Did you address any other issues? What I still saw is
- If there is no keyframe at the end, animation will get stuck to the end, and then reset as intended
- Left hand animation still seem to be problematic, just check `scml/run`. Compare it to the original if you have spriter installed, and you will see a big difference. What I noticed, and not sure if that can help you, but whenever the animation has this line, of some sort (not sure what it does, as I am new to Godot), the animation is stuck
![image](https://github.com/user-attachments/assets/0f69e111-1377-49fe-bd93-f7bfbcbe4541)


TBH speed is not that big of an issue, as we can easily increase the speed.

**Comment by wojtossfm** [comment]
@bnovakovic What you highlighted there was the effect of extra keys being added that shouldn't have been there. I've pushed a change to the https://github.com/wojtossfm/godot_scml_importer/tree/issue-32 branch that should address that. 

> but whenever the animation has this line

That is how it displays that it has the same value if I'm not mistaken. The SCML format is unfortunately poorly documented and a lot of what I'm doing is trying to guess the meaning and importance of certain elements of it. Having other plugins to compare against sometimes leads to clues but not always since these are always rooted in specific implementations/languages.

> If there is no keyframe at the end, animation will get stuck to the end, and then reset as intended

I wonder if this is one where the "loop wrap interpolation" import option would help it behave the way you expect?

**Comment by bnovakovic** [comment]
Hey @wojtossfm, seems like you resolved the issue with left hand which is awesome 👍. I also no longer see the errors in the console.

>I wonder if this is one where the "loop wrap interpolation" import option would help it behave the way you expect?

Can you clarify this one a bit? Where can I set this option? :)

**Comment by bnovakovic** [comment]
I see your last commit has set this `loop wrap interpolation` by default, but I still see the issue while testing. Did this fix it on your end?

**Comment by wojtossfm** [comment]
I'm not sure if the change to defaults would impact your already existing
files. In godot go to the import tab (by default next to scene hierarchy)
and you can change settings for a specific file (select it in the
filesystem view) and re-import.

**Comment by wojtossfm** [comment]
They should disappear. I'll try to have a look at it at some point this week.

**Comment by bnovakovic** [comment]
Animation name is "scml/die"

**Comment by wojtossfm** [comment]
It seems to be caused in part by the loop wrap interpolation (just had a quick look). I believe (haven't checked) you could fix it by "fixing" the animation to not be "looping" which means that the wrap interpolation isn't applied.

**Comment by wojtossfm** [comment]
Ah I see in part what the issue is - I'll need to rework my optimisation of animation - I remove repeating keys and I need to ensure I leave the first/last key rather than only the first. So should be possible to fix for the animation without editing the scml when I get around to it.

**Comment by bnovakovic** [comment]
> It seems to be caused in part by the loop wrap interpolation (just had a quick look). I believe (haven't checked) you could fix it by "fixing" the animation (in spriter/scml) to not be "looping" which means that the wrap interpolation isn't applied.
> 
> You can see what this looks like in the SCML for greyguy (looping=false)

Yup, setting `looping="false"` definetely makes the issue dissapear.

**Comment by wojtossfm** [comment]
So I've spotted the issue that was causing it and at least seems like in the "run" animation I also could run it without "loop wrap interpolation" because the keyframes were more correct now (though worth testing).

I also adjusted the speed logic and should now be correct - you may need to manually adjust the import setting of speed to 1 (change of default).

I've put these for now on a separate branch https://github.com/wojtossfm/godot_scml_importer/tree/issue-32-further-fixes

**Comment by bnovakovic** [comment]
@wojtossfm this actually looks much better. Now, non looping animations no longer loop, eyes issue in death animation are fixed and also issue where animation does not have end keyframe is fixed too. Nice job man. Tomorrow I will test my remaining animation and let you know if there are any issues. If not, we can close this one :)

**Comment by bnovakovic** [comment]
One more thing, in "stab" animation you also fixed how knife was showing up. It was dissapearing, probably because of loop wrap. But now it works fine.

**Comment by bnovakovic** [comment]
I can confirm that every SCML file, I have tested, works fine. Please make sure you test on your own, but I guess we can close this one :)

**Comment by wojtossfm** [comment]
Expected to be resolved with https://github.com/wojtossfm/godot_scml_importer/pull/33

**Comment by wojtossfm** [comment]
Thank you for taking the time to report these by the way. I'm hoping people will continue finding a use for the plugin. I'm conscious it still has a fair bit missing but the support I can currently provide it is focused around bug fixing as the amount of free time I end up having doesn't allow me to contribute anything more to it.
